### ISSUE TITLE
"npm install"  failed  and  build failed

### ISSUE THREAD

**Issue by sk3l10x1ng** [0xParrot/Parmy#1]
Hi  Parrot409,

First of all , thank you so much  for the awesome extension, used this extension during my pentest engagements, when i  tried to install and build the package it throws errors , tried to fix it but no results . THanks 

Tested on

1. node version :  20.9.0
2. npm version : 10.2.3

**ERROR:** 
npm ERR! code 1
npm ERR! path /Users/user/Parmy/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/bin/node /Users/user/Parmy/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/Users/user/Parmy/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@20.9.0 | darwin | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []

**Comment by parrot409** [comment]
Hi,
It's been three years since the last update of the plugin so I think some dependencies have to be updated. 
Maybe try building this with an older version of Node?

**Comment by parrot409** [comment]
Hi,
It's been three years since the last update of the plugin so I think some dependencies have to be updated.

You can also try building this an older version of Node.

**Comment by sk3l10x1ng** [comment]
Hi Parrot409,

Thanks , downgrading the node to version 10 , worked .

Once again thank you so much
